# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: FoodDX
email: your-email@example.com
description:  Get healthy, your way with FoodDX
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
logo: "images/logo/FoodDXByHolmusk_logo.svg"
twitter_username: jekyllrb
github_username:  jekyll

navbar:
- name: Our Nutrition Experts
  url: "/nutrition/"
- name: Holmusk
  url: "#"

hero:
  enable: true
  heroTitle:  Get healthy, your way with FoodDX
  herodescription: "Get insights on how to improve your diet with the help from our proprietary technology and personalised feedback from our nutrition experts."
  heroBtn: Learn More
  heroUrl: "#why"
  heroImage: "images/MainHomePage_Illustration.png"

why:
  enable: true
  title:  Why FoodDX?
  subTitle: "Our solution to help you transform the way you think and feel about food."
  image: "images/technology.png"
  lists:
  - icon: "images/icon.svg"
    title: Get real-time feedback on your meals
    info: >- 
        <p>Upload photos of your meal for real-time</p> 							<p>Nutrition scores and food tips.</p>
    mobTitle: Get real-time feedback on your meals
    mobInfo: >- 
      <p>Upload photos of your meal for real-time nutrition scores and food tips.</p>
  - icon: "images/icon.svg"
    title: Go at your own <br>pace
    info: >- 
        <p>Lasting change happens in the micro moments. We focus on these moments to help you reach your long-term goals.</p>
    mobTitle: Go at your own <br>pace
    mobInfo: >-
      <p>Lasting change happens in the micro moments. We focus on these moments to help you reach your long-term goals.</p>
  
technology:
  enable: true
  title: Our Technology
  image: "images/smartfoodtips.png"
  subTitle: >-
    <h6>FoodDX technology is based on <strong>behavioural modification </strong>strategies.</h6>
    <h6>Developed by nutrition experts at Holmusk for over 2 years, the platform uses clinically proven techniques to help you manage your diet and lead a healthier life.</h6>
  service:
  - icon: images/icon.svg
    title: AI Food Scoring
    lists:
    - text:  Artificial intelligence
    - text:  Real-time classification based on nutritional and health value
    - text:  Developed using cutting-edge computer vision
    - text:  Leverages on our real-world dataset of over 80,000 photos
  - icon: images/icon.svg
    title: Smart Tips for Better Health
    lists:
    - text:  Motivational content
    - text:  Engaging tips on how to improve your diet
    - text:  Meal recommendations
    - text:  Providing ways to move to higher star rating

holmuskSection:
  enable: true
  title: Transforming <br> lives through evidence-based medicine
  image: "images/smartfoodtips.png"
  subTitle: >-
    Looking to use FoodDX?
  info: >- 
    FoodDX is currently only available via our partner apps. <br><br> If you'd like to partner with us, please send us an email at <strong><a href="#">fooddx@holmusk.com.</a></strong></p>
  rightSide:
    heading: Supercharge your business with us
    description: Enhance your digital platforms with FoodDX. Use our API to <br>access our digital solutions.
    lists: 
    - icon: images/icon.svg
      title: Actionable approach for a healthier lifestyle
      desc: Measure and improve users’ dietary choices with instant feedback on meals and food tips for better health. 
    - icon: images/icon.svg
      title: Robust technology with extensive food database
      desc: Adaptable AI model built on our extensive food database, capable of supporting new regions and food cultures. 
    - icon: images/icon.svg
      title: Health management made easy
      desc: Effective lifestyle, weight and chronic disease management tools to improve users’ health.

footer:   
  logo: "/images/FoodDXLogo.svg"
  copyright: "Copyright &copy; 2020 Holmusk, Inc. <br class='d-block d-sm-none'> All rights reserved"  
  links:
  - name: "Terms &amp; Conditions"
    url: "/terms"
  - name: Privacy Policy
    url: "/privacy"

# Build settings
theme:
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
